### PR TITLE
STY: stylistic reformat with Intellij

### PR DESCRIPTION
**Pull request by eigenfoo**

### CODE REVIEW

**Comment by wside** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project euphoria: Compilation failure: Compilation failure:

**Comment by eigenfoo** [comment]
It was because of all the failing tests that were fixed in #71. Can you try again?

**Review by wside — APPROVED** [review]
tested, works. beep beep.

**Comment by eigenfoo** [comment]
I'm a 🐑

**Pull request merged**
